[package]
name = "moid_mercury"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
libc = "0.2.149"
reqwest = { version = "0.11.22", features = ["blocking"] }
